import type { Metadata } from 'next'
import { Inter, Outfit } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
})

export const metadata: Metadata = {
  title: 'Alex Ross',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="bg-gradient"
    >
      <body
        className={`${outfit.className} min-h-screen text-gray-50 flex flex-col items-center justify-center`}
      >
        <Navbar />
        <main className="w-full max-w-[1000px] mt-40 mb-40 flex flex-col gap-32">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
